# Generated by Django 4.1.3 on 2022-12-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="Olu's Blog", max_length=255),
        ),
    ]
