# Generated by Django 4.1.3 on 2022-12-21 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
