# Generated by Django 4.1.3 on 2023-10-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_profile_fb_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fb_url',
            new_name='facebook_url',
        ),
    ]
