# Generated by Django 4.1.3 on 2023-11-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_rename_fb_url_profile_facebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blogapp/imgs/default.jpg', null=True, upload_to='images/profile/'),
        ),
    ]
